Update jacoco.yml

diff --git a/.github/workflows/jacoco.yml b/.github/workflows/jacoco.yml
--- a/.github/workflows/jacoco.yml
+++ b/.github/workflows/jacoco.yml
@@ -2,6 +2,8 @@ name: Run JaCoCo
 
 on:
   push:
+    branches:
+      - main  # Adjust as necessary
 
 jobs:
   run-jacoco:
@@ -9,13 +11,13 @@ jobs:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [ubuntu-22.04, macos-latest]
+        os: [ubuntu-latest, macos-latest]
 
     steps:
     - name: Checkout repository
       uses: actions/checkout@v2
       with:
-        ref: af43a3e71f2bdb4765294f7d6314b1428737849d
+        ref: af43a3e71f2bdb4765294f7d6314b1428737849d  # Use the specific commit or branch
 
     - name: Set up JDK 17 for project
       uses: actions/setup-java@v3
@@ -24,83 +26,84 @@ jobs:
         java-version: '17'
         cache: maven
 
-    - name: Add Jacoco Maven Plugin and Edit Surefire Configuration
-      if: runner.os == 'Linux'
+    - name: Modify POM.xml for JaCoCo Plugin and Surefire Configuration
       run: |
-        sed -i '/<\/plugins>/i \
-          <plugin> \
-              <groupId>org.jacoco</groupId> \
-              <artifactId>jacoco-maven-plugin</artifactId> \
-              <version>0.8.11</version> \
-              <executions> \
-                  <execution> \
-                      <goals> \
-                          <goal>prepare-agent</goal> \
-                      </goals> \
-                      <configuration> \
-                        <outputDirectory>${project.basedir}/custom-jacoco-reports</outputDirectory> \
-                      </configuration> \
-                  </execution> \
-                  <execution> \
-                      <id>report</id> \
-                      <phase>test</phase> \
-                      <goals> \
-                          <goal>report</goal> \
-                      </goals> \
-                  </execution> \
-              </executions> \
-          </plugin>' pom.xml
-        sed -i '/<artifactId>maven-surefire-plugin<\/artifactId>/{N;s/<\/configuration>/<testFailureIgnore>true<\/testFailureIgnore><\/configuration>/;s/<configuration>/<configuration>/}' pom.xml || sed -i '/<artifactId>maven-surefire-plugin<\/artifactId>/a \
-          <configuration> \
-              <testFailureIgnore>true<\/testFailureIgnore> \
-          <\/configuration>' pom.xml
+        if [ -f "pom.xml" ]; then
+          if [[ ${{ matrix.os }} == 'ubuntu-latest' ]]; then
+            sed -i '{
+              /<\/plugins>/i \
+              <plugin> \
+                  <groupId>org.jacoco</groupId> \
+                  <artifactId>jacoco-maven-plugin</artifactId> \
+                  <version>0.8.11</version> \
+                  <executions> \
+                      <execution> \
+                          <goals> \
+                              <goal>prepare-agent</goal> \
+                          </goals> \
+                          <configuration> \
+                              <outputDirectory>${project.basedir}/custom-jacoco-reports</outputDirectory> \
+                          </configuration> \
+                      </execution> \
+                      <execution> \
+                          <id>report</id> \
+                          <phase>test</phase> \
+                          <goals> \
+                              <goal>report</goal> \
+                          </goals> \
+                      </execution> \
+                  </executions> \
+              </plugin>' pom.xml
 
-    - name: Add Jacoco Maven Plugin and Edit Surefire Configuration
-      if: runner.os == 'macOS'
-      run: |
-        sed -i '' '/<\/plugins>/i \
-          <plugin> \
-              <groupId>org.jacoco</groupId> \
-              <artifactId>jacoco-maven-plugin</artifactId> \
-              <version>0.8.11</version> \
-              <executions> \
-                  <execution> \
-                      <goals> \
-                          <goal>prepare-agent</goal> \
-                      </goals> \
-                      <configuration> \
-                        <outputDirectory>${project.basedir}/custom-jacoco-reports</outputDirectory> \
-                      </configuration> \
-                  </execution> \
-                  <execution> \
-                      <id>report</id> \
-                      <phase>test</phase> \
-                      <goals> \
-                          <goal>report</goal> \
-                      </goals> \
-                  </execution> \
-              </executions> \
-          </plugin>' pom.xml
-        sed -i '' '/<artifactId>maven-surefire-plugin<\/artifactId>/{N;s/<\/configuration>/<testFailureIgnore>true<\/testFailureIgnore><\/configuration>/;s/<configuration>/<configuration>/}' pom.xml || sed -i '' '/<artifactId>maven-surefire-plugin<\/artifactId>/a \
-          <configuration> \
-              <testFailureIgnore>true<\/testFailureIgnore> \
-          <\/configuration>' pom.xml
+            sed -i '/<artifactId>maven-surefire-plugin<\/artifactId>/a \
+              <configuration> \
+                  <testFailureIgnore>true<\/testFailureIgnore> \
+              <\/configuration>' pom.xml
+          elif [[ ${{ matrix.os }} == 'macos-latest' ]]; then
+            sed -i '' '/<\/plugins>/i \
+              <plugin> \
+                  <groupId>org.jacoco</groupId> \
+                  <artifactId>jacoco-maven-plugin</artifactId> \
+                  <version>0.8.11</version> \
+                  <executions> \
+                      <execution> \
+                          <goals> \
+                              <goal>prepare-agent</goal> \
+                          </goals> \
+                          <configuration> \
+                              <outputDirectory>${project.basedir}/custom-jacoco-reports</outputDirectory> \
+                          </configuration> \
+                      </execution> \
+                      <execution> \
+                          <id>report</id> \
+                          <phase>test</phase> \
+                          <goals> \
+                              <goal>report</goal> \
+                          </goals> \
+                      </execution> \
+                  </executions> \
+              </plugin>' pom.xml
+
+            sed -i '' '/<artifactId>maven-surefire-plugin<\/artifactId>/a \
+              <configuration> \
+                  <testFailureIgnore>true<\/testFailureIgnore> \
+              <\/configuration>' pom.xml
+          fi
+        else
+          echo "pom.xml not found"
+          exit 1
+        fi
 
     - name: Build project with JDK 17
       run: mvn test
 
-    - name: Export Jacoco Reports
-      run: |
-        mkdir -p custom-jacoco-reports
-        find . -name 'jacoco*.xml' -exec cp {} custom-jacoco-reports/ \;
-
     - name: Checkout Export Repository
       uses: actions/checkout@v2
       with:
-        repository: flaky-dynamic-testing/jacoco-exports 
-        token: ${{ secrets.GITHUB_TOKEN }} 
+        repository: flaky-dynamic-testing/jacoco-exports
+        token: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: Copy Jacoco Reports to new repository
+    - name: Copy JaCoCo Reports to new repository
       run: |
         REPO_NAME=$(basename $GITHUB_REPOSITORY)
         mkdir -p jacoco-exports/jacoco-reports-for-$REPO_NAME
@@ -109,5 +112,5 @@ jobs:
         git config user.email "actions@github.com"
         git config user.name "GitHub Actions"
         git add .
-        git commit -m "Add Jacoco reports for $REPO_NAME"
+        git commit -m "Add JaCoCo reports for $REPO_NAME"
         git push origin main
